--1. FIND OUT COUNTRY NAME AND REGION NAME FROM COUNTRIES AND
--REGION TABLE
select COUNTRY_NAME,REGION_NAME
from COUNTRIES join REGIONS
on COUNTRIES.REGION_ID = REGIONS.REGION_ID;


--2. FIND OUT FIRST_NAME AND JOB_TITLE FROM JOBS AND EMPLOYEES TABLE
select FIRST_NAME,JOB_TITLE
from EMPLOYEES join JOBS
on EMPLOYEES.JOB_ID = JOBS.JOB_ID;


--3. FIND OUT DEPARTMENT_NAME AND CITY
select DEPARTMENT_NAME,CITY
from DEPARTMENTS join LOCATIONS
on DEPARTMENTS.LOCATION_ID=LOCATIONS.LOCATION_ID;


--4. FIND OUT ALL CITIES AND COUNTRY NAMES
select city,COUNTRY_NAME
from LOCATIONS join COUNTRIES
on LOCATIONS.COUNTRY_ID=countries.COUNTRY_ID;


--5. FIND OUT FIRST_NAME, LAST NAME, DEPARTMENT ID , DEPARTMENT NAME
--FOR DEPARTMENT ID 80 OR 40
select FIRST_NAME,LAST_NAME,DEPARTMENT_ID,DEPARTMENT_NAME
from EMPLOYEES  join DEPARTMENTS
on EMPLOYEES.DEPARTMENT_ID=DEPARTMENTS.DEPARTMENT_ID
where EMPLOYEES.DEPARTMENT_ID in ('80') or EMPLOYEES.DEPARTMENT_ID in ('40');


--6. FIND OUT CITY , COUNTRY_NAME OF THAT CITY , REGION_NAME OF THAT CITY
select city,COUNTRY_NAME,REGION_NAME
from LOCATIONS join COUNTRIES
on locations.COUNTRY_ID=COUNTRIES.COUNTRY_ID
join REGIONS
on COUNTRIES.REGION_ID = REGIONS.REGION_ID;


--7. FIND OUT EMPLOYEES FIRST_NAME , JOB_TITLE , DEPARTMENT_NAME , CITY
select FIRST_NAME,JOB_TITLE,DEPARTMENT_NAME,CITY
from EMPLOYEES join JOBS
on EMPLOYEES.JOB_ID = JOBS.JOB_ID
join DEPARTMENTS
on EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
join LOCATIONS
on DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID;


--8. FIND OUT EMPLOYEES FIRST_NAME , JOB_TITLE , DEPARTMENT_NAME , CITY ,
--COUNTRY_NAME , REGION_NAME
select FIRST_NAME,JOB_TITLE,DEPARTMENT_NAME,city,COUNTRY_NAME,REGION_NAME
from EMPLOYEES E join JOBS J
on E.JOB_ID=j.JOB_ID
join DEPARTMENTS D
on e.DEPARTMENT_ID=d.DEPARTMENT_ID
join LOCATIONS L
on d.LOCATION_ID=l.LOCATION_ID
join COUNTRIES c
on l.COUNTRY_ID=c.COUNTRY_ID
join REGIONS r
on c.REGION_ID=r.REGION_ID;


--9. FIND OUR EMPLOYEES FIRST_NAME, LAST NAME, DEPARTMENT ID AND ALL
--DEPARTMENTS INCLUDING WHERE DO NOT HAVE ANY EMPLOYEE.


--10. FIND OUT ALL DEPARTMENT_NAME , LOCATION_ID , AND COUNTRY_ID
--INCLUDING THOSE LOCATIONS WITH NO DEPARTMENT
--11.FIND OUT DEPARTMENT_NAME , LOCATION_ID , AND COUNTRY_NAME
--INCLUDING THOSE COUNTRIES WITH NO DEPARTMENT
--12. FIND OUT EMPLOYEES FIRST_NAME, DEPARTMENT ID AND DEPARTMENT
--NAME INCLUDING THOSE DOES NOT HAVE DEPARTMENT, INCLUDING THOSE
--DEPARTMENTS DOES NOT HAVE ANY MATCHING EMPLOYEES